service: whitebrick-cloud
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  region: us-east-1
  profile: wb
  environment:
    APP: "whitebrick-cloud"
functions:
  graphql:
    handler: src/whitebrick-cloud.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  # bg:
  #   handler: src/whitebrick-cloud.bgHandler
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true
  serverless-offline:
    noTimeout: true
