service: whitebrick-cloud
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: wb
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true

