service: whitebrick-cloud
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  region: us-east-1
  profile: wb
  environment:
    APP: "whitebrick-cloud"
  vpc:
    securityGroupIds:
      - SECURITY_GROUP_1
      - SECURITY_GROUP_2
    subnetIds:
      - SUBNET_1
      - SUBNET_2
functions:
  graphql:
    handler: src/whitebrick-cloud.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  bg:
    handler: src/whitebrick-cloud.bgHandler
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true
  serverless-offline:
    noTimeout: true
